/*
ProjectEuler.net
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number is
1+2+3+4+5+6+7=28

the first ten terms would be 1,3,6,10,15,21,28,36,45,55,...

Let's list the factors of the first 7 triangle numbers

1:1
3:1,3
6:1,2,3,6
10:1,2,5,10
15:1,3,5,15
21:1,3,7,21
28:1,2,4,7,14,28

you can see that 28 is the first triangle number to have over 5 divisors

What is the value of the first triangle number to have over 500 divisors

*/

/*calculate the nth triangle number */
unsigned long int triangle(unsigned long int n){
	unsigned long int t=0;
	while(n) t+=n--;
	return t;
}

/* calculate the nth triangle number given n and triangle(n-1) */
unsigned long int next_triangle(unsigned long int n, unsigned long int last){
	return (last + n);
}

/* return the number of factors of t */
int factors(unsigned long int t){
	unsigned long int c;
	int f=0;
	for(c=1;c<=t;c++)
		if((t%c)==0)
			f++;
	return f;
}
/* C is the wrong language for this without implementing bignums, I get overruns in unsigned long */
