// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

#include <iostream>
using namespace std;

int main(){
  int c1 = 1;
  int c2 = 2;
  int c3 = 0;
  int sum = c2;
  while(c3 <= 4000000){
    if (!(c3%2))
      sum+= c3;
    c3 = c2 + c1;
    c1 = c2;
    c2 = c3;
  }
  cout<<sum<<endl;
  return 0;
}
